const GET_SELF = "GET_SELF";
const GET_CONNECTED_USERS = "GET_CONNECTED_USERS";
const UPDATE_USERNAME = "UPDATE_USERNAME";

module.exports = {
  GET_SELF,
  GET_CONNECTED_USERS,
  UPDATE_USERNAME,
};
