const GET_SELF = "GET_SELF";
const GET_CONNECTED_USERS = "GET_CONNECTED_USERS";
const UPDATE_USERNAME = "UPDATE_USERNAME";
const GET_LOBBIES = "GET_LOBBIES";
const GET_LOBBY = "GET_LOBBY";
const CREATE_LOBBY = "CREATE_LOBBY";
const JOIN_LOBBY = "JOIN_LOBBY";
const LEAVE_LOBBY = "LEAVE_LOBBY";
const UPDATE_LOBBY_NAME = "UPDATE_LOBBY_NAME";
const UPDATE_LOBBY_GAME_TIMER = "UPDATE_LOBBY_GAME_TIMER";
const TOGGLE_LOBBY_RANDOMIZE_SWITCH = "TOGGLE_LOBBY_RANDOMIZE_SWITCH";
const TOGGLE_LOBBY_PLAYER_READY_STATUS = "TOGGLE_LOBBY_PLAYER_READY_STATUS";

module.exports = {
  GET_SELF,
  GET_CONNECTED_USERS,
  UPDATE_USERNAME,
  GET_LOBBIES,
  GET_LOBBY,
  CREATE_LOBBY,
  JOIN_LOBBY,
  LEAVE_LOBBY,
  UPDATE_LOBBY_NAME,
  UPDATE_LOBBY_GAME_TIMER,
  TOGGLE_LOBBY_RANDOMIZE_SWITCH,
  TOGGLE_LOBBY_PLAYER_READY_STATUS,
};
