const GET_SELF = "GET_SELF";
const GET_CONNECTED_USERS = "GET_CONNECTED_USERS";
const UPDATE_USERNAME = "UPDATE_USERNAME";
const GET_LOBBIES = "GET_LOBBIES";
const GET_LOBBY = "GET_LOBBY";
const CREATE_LOBBY = "CREATE_LOBBY";

module.exports = {
  GET_SELF,
  GET_CONNECTED_USERS,
  UPDATE_USERNAME,
  GET_LOBBIES,
  GET_LOBBY,
  CREATE_LOBBY,
};
